openapi: 3.0.0
info:
  contact:
    email: manthan@keyconnect.app
    name: Manthan Dave
    url: https://www.manthanhd.com
  description: Blockchain access made simple
  license:
    name: The Apache License, Version 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.txt
  title: Key Connect API
  version: 1.1.0
servers:
- description: Production KeyConnect server
  url: https://api.keyconnect.app
- description: Local KeyConnect server
  url: http://localhost:8080
paths:
  /v1/server/status:
    get:
      description: Gets the Key Connect server status along with any error information.
      operationId: getServerStatus
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerStatusResponse'
          description: OK
      summary: Gets the Key Connect server status.
      tags:
      - server
      - status
      x-accepts: application/json
  /v1/blockchains/status:
    get:
      description: Key Connect server keeps track of the individual status of the
        supported blockchains. Use this API to check the blockchain statuses.
      operationId: getBlockchainsStatus
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailableBlockchains'
          description: OK
      summary: Gets a list of all supported blockchains and their statuses.
      tags:
      - blockchains
      - status
      x-accepts: application/json
  /v1/batch/blockchains/accounts/info:
    post:
      description: Batch call that returns details of all accounts in the request
        across all specified blockchains.
      operationId: getBlockchainsAccounts
      parameters:
      - description: Blockchain network to get the status from.
        explode: true
        in: query
        name: network
        required: false
        schema:
          example: testnet
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountsInfoRequest'
        description: List of accounts with their chainIds to get info for
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountsInfoResponse'
          description: OK
      summary: Gets account details of all specified accounts
      tags:
      - batch
      - blockchains
      - accounts
      x-contentType: application/json
      x-accepts: application/json
  /v1/blockchains/{chainId}/status:
    get:
      description: Gets status of the provided blockchain identified by `chainId`.
      operationId: getBlockchainStatus
      parameters:
      - description: ID of the block chain
        explode: false
        in: path
        name: chainId
        required: true
        schema:
          enum:
          - xrp
          - eth
          - btc
          type: string
        style: simple
      - description: Blockchain network to get the status from.
        explode: true
        in: query
        name: network
        required: false
        schema:
          example: testnet
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockchainStatus'
          description: OK
      summary: Returns the status of the provided blockchain.
      tags:
      - blockchains
      - status
      x-accepts: application/json
  /v1/blockchains/{chainId}/fee:
    get:
      description: Gets fee of the provided blockchain identified by `chainId`.
      operationId: getFee
      parameters:
      - description: ID of the block chain
        explode: false
        in: path
        name: chainId
        required: true
        schema:
          enum:
          - xrp
          - eth
          - btc
          type: string
        style: simple
      - description: Blockchain network to get the status from.
        explode: true
        in: query
        name: network
        required: false
        schema:
          example: testnet
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockchainFee'
          description: OK
      summary: Returns the blockchain transaction fee.
      tags:
      - blockchains
      x-accepts: application/json
  /v1/blockchains/{chainId}/accounts/{accountId}:
    get:
      description: Gets account / wallet information like `balance`, `lastTransactionId`
        etc of the specified blockchain identified by `chainId`.
      operationId: getAccountInfo
      parameters:
      - description: ID of the block chain
        explode: false
        in: path
        name: chainId
        required: true
        schema:
          enum:
          - xrp
          - eth
          - btc
          example: xrp
          type: string
        style: simple
      - description: ' Blockchain network to get the account info from. For example,
          for XRP this would be one of (testnet/devnet/mainnet). More information
          regarding what environments are available can be obtained from /v1/blockchains/{chainId}/status
          endpoint. '
        explode: true
        in: query
        name: network
        required: false
        schema:
          default: mainnet
          example: testnet
          type: string
        style: form
      - description: Identifier representing the account. This is most likely the
          wallet address.
        explode: false
        in: path
        name: accountId
        required: true
        schema:
          example: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
          type: string
        style: simple
      - description: Used to provide equivalent value in specified fiat
        explode: true
        in: query
        name: fiat
        required: false
        schema:
          enum:
          - USD
          - GBP
          - EUR
          example: USD
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockchainAccountInfo'
          description: OK
      summary: Returns account / wallet information for the provided `chainId` representing
        the blockchain.
      tags:
      - blockchains
      - accounts
      x-accepts: application/json
  /v1/blockchains/{chainId}/accounts/{accountId}/transactions:
    get:
      description: Gets transactions for given `accountId` on a given blockchain identified
        by the `chainId` parameter. Return the `cursor` value in the next call to
        get the next page.
      operationId: getAccountTransactions
      parameters:
      - example: xrp
        explode: false
        in: path
        name: chainId
        required: true
        schema:
          enum:
          - xrp
          - eth
          - btc
          type: string
        style: simple
      - description: ' Blockchain network to get the account info from. For example,
          for XRP this would be one of (testnet/devnet/mainnet). More information
          regarding what environments are available can be obtained from /v1/blockchains/{chainId}/status
          endpoint. '
        explode: true
        in: query
        name: network
        required: false
        schema:
          default: mainnet
          example: testnet
          type: string
        style: form
      - description: Identifier representing the account. This is most likely the
          wallet address.
        explode: false
        in: path
        name: accountId
        required: true
        schema:
          example: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
          type: string
        style: simple
      - description: Cursor representing position among pages. Pass the cursor from
          previous get transactions response to get the next page.
        explode: true
        in: query
        name: cursor
        required: false
        schema:
          description: Format varies by the blockchain. For XRP, the value of `cursor`
            will be the `ledger:seq` from the marker object.
          example: 57112007:13
          type: string
        style: form
      - description: Used to provide equivalent value in specified fiat
        explode: true
        in: query
        name: fiat
        required: false
        schema:
          enum:
          - USD
          - GBP
          - EUR
          example: USD
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockchainAccountTransactions'
          description: OK
      summary: Returns paginated list of transactions.
      tags:
      - blockchains
      - accounts
      - transactions
      x-accepts: application/json
  /v1/blockchains/{chainId}/accounts/{accountId}/payments:
    get:
      description: Gets payments for given `accountId` on a given blockchain identified
        by the `chainId` parameter. Return the `cursor` value in the next call to
        get the next page.
      operationId: getAccountPayments
      parameters:
      - example: xrp
        explode: false
        in: path
        name: chainId
        required: true
        schema:
          enum:
          - xrp
          - eth
          - btc
          type: string
        style: simple
      - description: ' Blockchain network to get the account info from. For example,
          for XRP this would be one of (testnet/devnet/mainnet). More information
          regarding what environments are available can be obtained from /v1/blockchains/{chainId}/status
          endpoint. '
        explode: true
        in: query
        name: network
        required: false
        schema:
          default: mainnet
          example: testnet
          type: string
        style: form
      - description: Identifier representing the account. This is most likely the
          wallet address.
        explode: false
        in: path
        name: accountId
        required: true
        schema:
          example: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
          type: string
        style: simple
      - description: Cursor representing position among pages. Pass the cursor from
          previous get payments response to get the next page.
        explode: true
        in: query
        name: cursor
        required: false
        schema:
          description: Format varies by the blockchain. For XRP, the value of `cursor`
            will be the `ledger:seq` from the marker object.
          example: 57112007:13
          type: string
        style: form
      - description: Used to provide equivalent value in specified fiat
        explode: true
        in: query
        name: fiat
        required: false
        schema:
          enum:
          - USD
          - GBP
          - EUR
          example: USD
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockchainAccountPayments'
          description: OK
      summary: Returns paginated list of payments.
      tags:
      - blockchains
      - accounts
      - payments
      x-accepts: application/json
  /v1/blockchains/{chainId}/transactions/{hash}:
    get:
      description: Returned transaction object might be in greater detail than the
        one provided in the list.
      operationId: getTransaction
      parameters:
      - explode: false
        in: path
        name: chainId
        required: true
        schema:
          enum:
          - xrp
          - eth
          - btc
          type: string
        style: simple
      - description: Hash of the transaction to lookup
        explode: false
        in: path
        name: hash
        required: true
        schema:
          type: string
        style: simple
      - description: ' Blockchain network to get the account info from. For example,
          for XRP this would be one of (testnet/devnet/mainnet). More information
          regarding what environments are available can be obtained from /v1/blockchains/{chainId}/status
          endpoint. '
        explode: true
        in: query
        name: network
        required: false
        schema:
          default: mainnet
          example: testnet
          type: string
        style: form
      - description: Used to provide equivalent value in specified fiat
        explode: true
        in: query
        name: fiat
        required: false
        schema:
          enum:
          - USD
          - GBP
          - EUR
          example: USD
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockchainAccountTransaction'
          description: OK
      summary: Get a single transaction object by its provided `hash` on the specified
        `chainId`.
      tags:
      - blockchains
      - transactions
      x-accepts: application/json
  /v1/blockchains/{chainId}/transactions:
    post:
      description: Provided transaction object is submitted directly to the blockchain
        identified by `chainId` as is.
      operationId: submitTransaction
      parameters:
      - explode: false
        in: path
        name: chainId
        required: true
        schema:
          enum:
          - xrp
          - eth
          - btc
          type: string
        style: simple
      - description: ' Blockchain network to get the account info from. For example,
          for XRP this would be one of (testnet/devnet/mainnet). More information
          regarding what environments are available can be obtained from /v1/blockchains/{chainId}/status
          endpoint. '
        explode: true
        in: query
        name: network
        required: false
        schema:
          default: mainnet
          example: testnet
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitTransactionRequest'
        description: Request payload containing the transaction to submit to specified
          `chainId`.
      responses:
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmitTransactionResult'
          description: Accepted
      summary: Submit a transaction to the blockchain.
      tags:
      - blockchains
      - transactions
      x-contentType: application/json
      x-accepts: application/json
  /v1/blockchains/xrp/generator/payment:
    get:
      description: Helper method to generate a transaction object for the purpose
        of a payment between the source account identified by `sourceAccount` and
        destination account idenfied by `destinationAccount` for the value of `amount`.
      operationId: generateXrpTransaction
      parameters:
      - description: Source account
        explode: true
        in: query
        name: sourceAccount
        required: true
        schema:
          example: rPT1Sjq2YGrBMTttX4GZHjKu9dyfzbpAYe
          type: string
        style: form
      - description: Destination account
        explode: true
        in: query
        name: destinationAccount
        required: true
        schema:
          example: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
          type: string
        style: form
      - description: Destination tag
        explode: true
        in: query
        name: destinationTag
        required: false
        schema:
          example: 58871619
          type: number
        style: form
      - description: Payment amount in drops
        explode: true
        in: query
        name: amount
        required: true
        schema:
          example: "10000000"
          type: string
        style: form
      - description: Fee to the ledger in drops. If this field is omitted, then `network`
          must be specified.
        explode: true
        in: query
        name: fee
        required: false
        schema:
          example: "5200"
          type: string
        style: form
      - description: ' Blockchain network to get the account info from. For XRP this
          would be one of (testnet/devnet/mainnet). More information regarding what
          environments are available can be obtained from /v1/blockchains/{chainId}/status
          endpoint. This field is required if `fee` is not specified in order to dynamically
          obtain the fee from the network. '
        explode: true
        in: query
        name: network
        required: false
        schema:
          default: mainnet
          example: testnet
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
          description: OK
      summary: Generates a transaction as a payment.
      tags:
      - blockchains
      - generator
      x-accepts: application/json
  /v1/rates/{base}/{counter}:
    get:
      description: Returns the applicable rate to convert between the provided base
        and counter currency.
      operationId: getRate
      parameters:
      - description: Base currency
        example: ETH
        explode: false
        in: path
        name: base
        required: true
        schema:
          type: string
        style: simple
      - description: Counter currency
        example: USD
        explode: false
        in: path
        name: counter
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RateResponse'
          description: OK
      summary: Gets the currency conversion rate for the provided base and counter
        currency.
      tags:
      - rates
      x-accepts: application/json
components:
  schemas:
    ServerStatusResponse:
      description: Represents the status of the Key Connect server.
      example:
        errors:
        - severity: critical
          category: blockchain
          message: message
        - severity: critical
          category: blockchain
          message: message
        status: healthy
      properties:
        status:
          description: Status of the server
          enum:
          - healthy
          - unhealthy
          type: string
        errors:
          description: Any server errors if the server is unhealthy
          items:
            $ref: '#/components/schemas/ServerStatusResponse_errors'
          type: array
    BlockchainStatusResponse:
      description: Represents the status of the block chain. This object is cached
        as per the `lastCheck` attribute.
      properties:
        status:
          description: Status of the block chain
          enum:
          - connected
          - disconnected
          type: string
        lastCheck:
          description: UTC timestamp representing when the status was last checked
          type: string
    ServerErrorObject:
      description: Represents information regarding a error.
      example:
        severity: critical
        category: blockchain
        message: message
      properties:
        category:
          description: Error category
          enum:
          - blockchain
          - database
          - internal
          type: string
        severity:
          description: Error severity
          enum:
          - critical
          - high
          - medium
          - low
          - warning
          - info
          type: string
        message:
          description: Error message
          type: string
    AvailableBlockchains:
      description: List of available blockchains and their statuses
      example:
        blockchains:
        - chainId: xrp
          networks:
          - servers:
            - lastCheck: 2020-09-20 08:32:20
              host: host
              status: healthy
            - lastCheck: 2020-09-20 08:32:20
              host: host
              status: healthy
            group: testnet
          - servers:
            - lastCheck: 2020-09-20 08:32:20
              host: host
              status: healthy
            - lastCheck: 2020-09-20 08:32:20
              host: host
              status: healthy
            group: testnet
        - chainId: xrp
          networks:
          - servers:
            - lastCheck: 2020-09-20 08:32:20
              host: host
              status: healthy
            - lastCheck: 2020-09-20 08:32:20
              host: host
              status: healthy
            group: testnet
          - servers:
            - lastCheck: 2020-09-20 08:32:20
              host: host
              status: healthy
            - lastCheck: 2020-09-20 08:32:20
              host: host
              status: healthy
            group: testnet
      properties:
        blockchains:
          items:
            $ref: '#/components/schemas/BlockchainStatus'
          type: array
    BlockchainStatus:
      description: Represents a blockchain and its status.
      example:
        chainId: xrp
        networks:
        - servers:
          - lastCheck: 2020-09-20 08:32:20
            host: host
            status: healthy
          - lastCheck: 2020-09-20 08:32:20
            host: host
            status: healthy
          group: testnet
        - servers:
          - lastCheck: 2020-09-20 08:32:20
            host: host
            status: healthy
          - lastCheck: 2020-09-20 08:32:20
            host: host
            status: healthy
          group: testnet
      properties:
        chainId:
          example: xrp
          type: string
        networks:
          items:
            $ref: '#/components/schemas/BlockchainNetwork'
          type: array
    BlockchainNetwork:
      description: Blockchain network object identifying the group and the list of
        servers under this group.
      example:
        servers:
        - lastCheck: 2020-09-20 08:32:20
          host: host
          status: healthy
        - lastCheck: 2020-09-20 08:32:20
          host: host
          status: healthy
        group: testnet
      properties:
        group:
          example: testnet
          type: string
        servers:
          items:
            $ref: '#/components/schemas/BlockchainNetworkServerStatus'
          type: array
    BlockchainNetworkServerStatus:
      description: Represents status of a blockchain network.
      example:
        lastCheck: 2020-09-20 08:32:20
        host: host
        status: healthy
      properties:
        host:
          type: string
        status:
          enum:
          - healthy
          - unhealthy
          type: string
        lastCheck:
          example: 2020-09-20 08:32:20
          type: string
    BlockchainAccountInfo:
      description: Represents information regarding a blockchain wallet / account.
      example:
        server: https://s.altnet.rippletest.net:51234/
        accountId: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
        subAccounts:
        - accountId: 0xfF20817765cB7f73d4bde2e66e067E58D11095C2
          balance:
            amount: amount
            currency: currency
            issuer: issuer
          value:
            amount: amount
            currency: currency
            issuer: issuer
        - accountId: 0xfF20817765cB7f73d4bde2e66e067E58D11095C2
          balance:
            amount: amount
            currency: currency
            issuer: issuer
          value:
            amount: amount
            currency: currency
            issuer: issuer
        balance:
          amount: amount
          currency: xrp
          issuer: issuer
        chainId: xrp
        lastTransactionId: 4294BEBE5B569A18C0A2702387C9B1E7146DC3A5850C1E87204951C6FDAA4C42
        value:
          amount: amount
          currency: currency
          issuer: issuer
        errors:
        - severity: critical
          category: blockchain
          message: message
        - severity: critical
          category: blockchain
          message: message
        network: testnet
      properties:
        chainId:
          enum:
          - xrp
          - eth
          - btc
          type: string
        network:
          example: testnet
          type: string
        server:
          example: https://s.altnet.rippletest.net:51234/
          type: string
        accountId:
          example: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
          type: string
        balance:
          $ref: '#/components/schemas/CurrencyValue'
        value:
          $ref: '#/components/schemas/GenericCurrencyValue'
        subAccounts:
          description: List of sub accounts and their balances. ERC20 tokens and their
            balances in case of ethereum.
          items:
            $ref: '#/components/schemas/SubAccountInfo'
          type: array
        lastTransactionId:
          example: 4294BEBE5B569A18C0A2702387C9B1E7146DC3A5850C1E87204951C6FDAA4C42
          type: string
        errors:
          items:
            $ref: '#/components/schemas/ServerErrorObject'
          type: array
    CurrencyValue:
      description: Simple object representing `amount` as string in a specific `currency`.
      example:
        amount: amount
        currency: xrp
        issuer: issuer
      properties:
        amount:
          type: string
        issuer:
          nullable: true
          type: string
        currency:
          enum:
          - xrp
          - drops
          - eth
          - gas
          type: string
      required:
      - amount
      - currency
    BlockchainAccountTransactions:
      description: List of transactions for a specified blockchain account / wallet
        within the specified `cursor`.
      example:
        cursor: 57112007:13
        server: https://s.altnet.rippletest.net:51234/
        accountId: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
        chainId: xrp
        transactions:
        - amount:
            amount: amount
            currency: xrp
            issuer: issuer
          sourceAccount: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
          destinationTag: "255577"
          fee:
            amount: amount
            currency: xrp
            issuer: issuer
          type: Payment
          value:
            amount: amount
            currency: currency
            issuer: issuer
          destinationAccount: rU2mEJSLqBRkYLVTv55rFTgQajkLTnT6mA
          hash: 558FB77C856092E191D3117C13A1BDB299050B5140CDF6916F50F026620463FE
          status: success
        - amount:
            amount: amount
            currency: xrp
            issuer: issuer
          sourceAccount: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
          destinationTag: "255577"
          fee:
            amount: amount
            currency: xrp
            issuer: issuer
          type: Payment
          value:
            amount: amount
            currency: currency
            issuer: issuer
          destinationAccount: rU2mEJSLqBRkYLVTv55rFTgQajkLTnT6mA
          hash: 558FB77C856092E191D3117C13A1BDB299050B5140CDF6916F50F026620463FE
          status: success
        network: testnet
      properties:
        chainId:
          enum:
          - xrp
          - eth
          - btc
          type: string
        network:
          example: testnet
          type: string
        server:
          example: https://s.altnet.rippletest.net:51234/
          type: string
        accountId:
          example: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
          type: string
        cursor:
          description: Format varies by the blockchain. For XRP, the value of `cursor`
            will be the `ledger:seq` from the marker object. This value is null when
            there are no more pages.
          example: 57112007:13
          type: string
        transactions:
          items:
            $ref: '#/components/schemas/BlockchainAccountTransactionItem'
          type: array
    BlockchainAccountTransactionItem:
      description: Individual transaction for a specific blockchain account / wallet.
      example:
        amount:
          amount: amount
          currency: xrp
          issuer: issuer
        sourceAccount: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
        destinationTag: "255577"
        fee:
          amount: amount
          currency: xrp
          issuer: issuer
        type: Payment
        value:
          amount: amount
          currency: currency
          issuer: issuer
        destinationAccount: rU2mEJSLqBRkYLVTv55rFTgQajkLTnT6mA
        hash: 558FB77C856092E191D3117C13A1BDB299050B5140CDF6916F50F026620463FE
        status: success
      properties:
        status:
          description: One of `success`, `failure` or `pending` in most cases. In
            case the server returns unusual status, this attribute will reflect the
            raw value.
          example: success
          type: string
        type:
          example: Payment
          type: string
        sourceAccount:
          example: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
          type: string
        destinationAccount:
          example: rU2mEJSLqBRkYLVTv55rFTgQajkLTnT6mA
          type: string
        destinationTag:
          example: "255577"
          type: string
        fee:
          $ref: '#/components/schemas/CurrencyValue'
        amount:
          $ref: '#/components/schemas/CurrencyValue'
        value:
          $ref: '#/components/schemas/GenericCurrencyValue'
        hash:
          example: 558FB77C856092E191D3117C13A1BDB299050B5140CDF6916F50F026620463FE
          type: string
    BlockchainAccountTransaction:
      description: Represents a blockchain account transaction.
      example:
        server: https://s.altnet.rippletest.net:51234/
        chainId: xrp
        transaction:
          amount:
            amount: amount
            currency: xrp
            issuer: issuer
          sourceAccount: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
          destinationTag: "255577"
          fee:
            amount: amount
            currency: xrp
            issuer: issuer
          type: Payment
          value:
            amount: amount
            currency: currency
            issuer: issuer
          destinationAccount: rU2mEJSLqBRkYLVTv55rFTgQajkLTnT6mA
          hash: 558FB77C856092E191D3117C13A1BDB299050B5140CDF6916F50F026620463FE
          status: success
        network: testnet
      properties:
        chainId:
          enum:
          - xrp
          - eth
          - btc
          type: string
        network:
          example: testnet
          type: string
        server:
          example: https://s.altnet.rippletest.net:51234/
          type: string
        transaction:
          $ref: '#/components/schemas/BlockchainAccountTransactionItem'
    SubmitTransactionRequest:
      example:
        transaction: 1200002280000000240000001E61D4838D7EA4C6800000000000000000000000000055534400000000004B4E9C06F24296074F7BC48F92A97916C6DC5EA968400000000000000B732103AB40A0490F9B7ED8DF29D246BF2D6269820A0EE7742ACDD457BEA7C7D0931EDB7447304502210095D23D8AF107DF50651F266259CC7139D0CD0C64ABBA3A958156352A0D95A21E02207FCF9B77D7510380E49FF250C21B57169E14E9B4ACFD314CEDC79DDD0A38B8A681144B4E9C06F24296074F7BC48F92A97916C6DC5EA983143E9D4A2B8AA0780F682D136F7A56D6724EF53754
      properties:
        transaction:
          description: The transaction blob as required by the blockchain you are
            submitting to.
          example: 1200002280000000240000001E61D4838D7EA4C6800000000000000000000000000055534400000000004B4E9C06F24296074F7BC48F92A97916C6DC5EA968400000000000000B732103AB40A0490F9B7ED8DF29D246BF2D6269820A0EE7742ACDD457BEA7C7D0931EDB7447304502210095D23D8AF107DF50651F266259CC7139D0CD0C64ABBA3A958156352A0D95A21E02207FCF9B77D7510380E49FF250C21B57169E14E9B4ACFD314CEDC79DDD0A38B8A681144B4E9C06F24296074F7BC48F92A97916C6DC5EA983143E9D4A2B8AA0780F682D136F7A56D6724EF53754
          type: string
    SubmitTransactionResult:
      description: Represents the result of the submission of a given blockchain transaction.
      example:
        server: https://s.altnet.rippletest.net:51234/
        chainId: xrp
        transaction:
          amount:
            amount: amount
            currency: xrp
            issuer: issuer
          sourceAccount: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
          destinationTag: "255577"
          fee:
            amount: amount
            currency: xrp
            issuer: issuer
          type: Payment
          value:
            amount: amount
            currency: currency
            issuer: issuer
          destinationAccount: rU2mEJSLqBRkYLVTv55rFTgQajkLTnT6mA
          hash: 558FB77C856092E191D3117C13A1BDB299050B5140CDF6916F50F026620463FE
          status: success
        network: testnet
      properties:
        chainId:
          enum:
          - xrp
          - eth
          - btc
          type: string
        network:
          example: testnet
          type: string
        server:
          example: https://s.altnet.rippletest.net:51234/
          type: string
        transaction:
          $ref: '#/components/schemas/BlockchainAccountTransactionItem'
    BlockchainAccountPayments:
      example:
        cursor: 57112007:13
        server: https://s.altnet.rippletest.net:51234/
        accountId: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
        chainId: xrp
        payments:
        - amount:
            amount: amount
            currency: xrp
            issuer: issuer
          sourceAccount: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
          destinationTag: "255577"
          fee:
            amount: amount
            currency: xrp
            issuer: issuer
          value:
            amount: amount
            currency: currency
            issuer: issuer
          destinationAccount: rU2mEJSLqBRkYLVTv55rFTgQajkLTnT6mA
          hash: 558FB77C856092E191D3117C13A1BDB299050B5140CDF6916F50F026620463FE
          status: success
        - amount:
            amount: amount
            currency: xrp
            issuer: issuer
          sourceAccount: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
          destinationTag: "255577"
          fee:
            amount: amount
            currency: xrp
            issuer: issuer
          value:
            amount: amount
            currency: currency
            issuer: issuer
          destinationAccount: rU2mEJSLqBRkYLVTv55rFTgQajkLTnT6mA
          hash: 558FB77C856092E191D3117C13A1BDB299050B5140CDF6916F50F026620463FE
          status: success
        network: testnet
      properties:
        chainId:
          enum:
          - xrp
          - eth
          - btc
          type: string
        network:
          example: testnet
          type: string
        server:
          example: https://s.altnet.rippletest.net:51234/
          type: string
        accountId:
          example: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
          type: string
        cursor:
          description: Format varies by the blockchain. For XRP, the value of `cursor`
            will be the `ledger:seq` from the marker object. This value is null when
            there are no more pages.
          example: 57112007:13
          type: string
        payments:
          items:
            $ref: '#/components/schemas/BlockchainAccountPaymentItem'
          type: array
    BlockchainAccountPaymentItem:
      example:
        amount:
          amount: amount
          currency: xrp
          issuer: issuer
        sourceAccount: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
        destinationTag: "255577"
        fee:
          amount: amount
          currency: xrp
          issuer: issuer
        value:
          amount: amount
          currency: currency
          issuer: issuer
        destinationAccount: rU2mEJSLqBRkYLVTv55rFTgQajkLTnT6mA
        hash: 558FB77C856092E191D3117C13A1BDB299050B5140CDF6916F50F026620463FE
        status: success
      properties:
        status:
          description: One of `success`, `failure` or `pending` in most cases. In
            case the server returns unusual status, this attribute will reflect the
            raw value.
          example: success
          type: string
        sourceAccount:
          example: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
          type: string
        destinationAccount:
          example: rU2mEJSLqBRkYLVTv55rFTgQajkLTnT6mA
          type: string
        destinationTag:
          example: "255577"
          type: string
        fee:
          $ref: '#/components/schemas/CurrencyValue'
        amount:
          $ref: '#/components/schemas/CurrencyValue'
        value:
          $ref: '#/components/schemas/GenericCurrencyValue'
        hash:
          example: 558FB77C856092E191D3117C13A1BDB299050B5140CDF6916F50F026620463FE
          type: string
    BlockchainFee:
      description: Blockchain fee.
      example:
        server: https://s.altnet.rippletest.net:51234/
        chainId: xrp
        fee:
          amount: amount
          currency: xrp
          issuer: issuer
        network: testnet
      properties:
        chainId:
          enum:
          - xrp
          - eth
          - btc
          type: string
        network:
          example: testnet
          type: string
        server:
          example: https://s.altnet.rippletest.net:51234/
          type: string
        fee:
          $ref: '#/components/schemas/CurrencyValue'
    SubAccountInfo:
      description: Represents a sub-account. ERC20 token account in case of ethereum.
      example:
        accountId: 0xfF20817765cB7f73d4bde2e66e067E58D11095C2
        balance:
          amount: amount
          currency: currency
          issuer: issuer
        value:
          amount: amount
          currency: currency
          issuer: issuer
      properties:
        accountId:
          description: ID of the sub account. Contract hash in case of ethereum token.
          example: 0xfF20817765cB7f73d4bde2e66e067E58D11095C2
          type: string
        balance:
          $ref: '#/components/schemas/GenericCurrencyValue'
        value:
          $ref: '#/components/schemas/GenericCurrencyValue'
    ExceptionalResponse:
      properties:
        timestamp:
          example: 1609519112841
          type: number
        status:
          example: 400
          type: integer
        error:
          example: Bad Request
          type: string
        message:
          example: Specified network is not a valid network for the block chain
          type: string
        path:
          example: /v1/blockchains/xrp/accounts/rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv/transactions
          type: string
    GenericCurrencyValue:
      example:
        amount: amount
        currency: currency
        issuer: issuer
      properties:
        amount:
          type: string
        issuer:
          nullable: true
          type: string
        currency:
          type: string
    AccountsInfoRequest:
      example:
        accounts:
        - accountId: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
          chainId: xrp
          network: mainnet
        - accountId: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
          chainId: xrp
          network: mainnet
      properties:
        accounts:
          items:
            $ref: '#/components/schemas/AccountsInfoRequestItem'
          type: array
    AccountsInfoResponse:
      example:
        accounts:
        - server: https://s.altnet.rippletest.net:51234/
          accountId: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
          subAccounts:
          - accountId: 0xfF20817765cB7f73d4bde2e66e067E58D11095C2
            balance:
              amount: amount
              currency: currency
              issuer: issuer
            value:
              amount: amount
              currency: currency
              issuer: issuer
          - accountId: 0xfF20817765cB7f73d4bde2e66e067E58D11095C2
            balance:
              amount: amount
              currency: currency
              issuer: issuer
            value:
              amount: amount
              currency: currency
              issuer: issuer
          balance:
            amount: amount
            currency: xrp
            issuer: issuer
          chainId: xrp
          lastTransactionId: 4294BEBE5B569A18C0A2702387C9B1E7146DC3A5850C1E87204951C6FDAA4C42
          value:
            amount: amount
            currency: currency
            issuer: issuer
          errors:
          - severity: critical
            category: blockchain
            message: message
          - severity: critical
            category: blockchain
            message: message
          network: testnet
        - server: https://s.altnet.rippletest.net:51234/
          accountId: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
          subAccounts:
          - accountId: 0xfF20817765cB7f73d4bde2e66e067E58D11095C2
            balance:
              amount: amount
              currency: currency
              issuer: issuer
            value:
              amount: amount
              currency: currency
              issuer: issuer
          - accountId: 0xfF20817765cB7f73d4bde2e66e067E58D11095C2
            balance:
              amount: amount
              currency: currency
              issuer: issuer
            value:
              amount: amount
              currency: currency
              issuer: issuer
          balance:
            amount: amount
            currency: xrp
            issuer: issuer
          chainId: xrp
          lastTransactionId: 4294BEBE5B569A18C0A2702387C9B1E7146DC3A5850C1E87204951C6FDAA4C42
          value:
            amount: amount
            currency: currency
            issuer: issuer
          errors:
          - severity: critical
            category: blockchain
            message: message
          - severity: critical
            category: blockchain
            message: message
          network: testnet
        network: network
      properties:
        network:
          type: string
        accounts:
          items:
            $ref: '#/components/schemas/BlockchainAccountInfo'
          type: array
    AccountsInfoRequestItem:
      example:
        accountId: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
        chainId: xrp
        network: mainnet
      properties:
        chainId:
          description: ID of the block chain
          enum:
          - xrp
          - eth
          example: xrp
          type: string
        network:
          default: mainnet
          description: ' Blockchain network to get the account info from. For XRP
            this would be one of (testnet/devnet/mainnet). More information regarding
            what environments are available can be obtained from /v1/blockchains/{chainId}/status
            endpoint. This field is required if `fee` is not specified in order to
            dynamically obtain the fee from the network. '
          type: string
        accountId:
          description: Identifier representing the account. This is most likely the
            wallet address.
          example: rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv
          type: string
      required:
      - accountId
      - chainId
    Rate:
      example:
        price: "1500"
        counter: USD
        base: ETH
      properties:
        base:
          description: Base currency
          example: ETH
          type: string
        counter:
          description: Counter currency
          example: USD
          type: string
        price:
          description: Rate to convert the base currency into the counter currency
          example: "1500"
          type: string
    RateResponse:
      example:
        avg:
          price: "1500"
          counter: USD
          base: ETH
      properties:
        avg:
          $ref: '#/components/schemas/Rate'
    ServerStatusResponse_errors:
      description: Array object
      example:
        severity: critical
        category: blockchain
        message: message
      properties:
        category:
          description: Error category
          enum:
          - blockchain
          - database
          - internal
          type: string
        severity:
          description: Error severity
          enum:
          - critical
          - high
          - medium
          - low
          - warning
          - info
          type: string
        message:
          description: Error message
          type: string
      type: object

